//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6demo.OperationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purse", Namespace="http://schemas.datacontract.org/2004/07/financialplanner.Data")]
    [System.SerializableAttribute()]
    public partial class Purse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CurrentBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lab6demo.OperationServiceReference.Operation[] OperationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurseCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lab6demo.OperationServiceReference.PurseState _purseStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CurrentBalance {
            get {
                return this.CurrentBalanceField;
            }
            set {
                if ((this.CurrentBalanceField.Equals(value) != true)) {
                    this.CurrentBalanceField = value;
                    this.RaisePropertyChanged("CurrentBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lab6demo.OperationServiceReference.Operation[] Operations {
            get {
                return this.OperationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationsField, value) != true)) {
                    this.OperationsField = value;
                    this.RaisePropertyChanged("Operations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PurseCurrency {
            get {
                return this.PurseCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.PurseCurrencyField, value) != true)) {
                    this.PurseCurrencyField = value;
                    this.RaisePropertyChanged("PurseCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Report {
            get {
                return this.ReportField;
            }
            set {
                if ((this.ReportField.Equals(value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lab6demo.OperationServiceReference.PurseState _purseState {
            get {
                return this._purseStateField;
            }
            set {
                if ((object.ReferenceEquals(this._purseStateField, value) != true)) {
                    this._purseStateField = value;
                    this.RaisePropertyChanged("_purseState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurseState", Namespace="http://schemas.datacontract.org/2004/07/financialplanner.Data")]
    [System.SerializableAttribute()]
    public partial class PurseState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lab6demo.OperationServiceReference.Purse PurseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lab6demo.OperationServiceReference.Purse Purse {
            get {
                return this.PurseField;
            }
            set {
                if ((object.ReferenceEquals(this.PurseField, value) != true)) {
                    this.PurseField = value;
                    this.RaisePropertyChanged("Purse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operation", Namespace="http://schemas.datacontract.org/2004/07/financialplanner.Data")]
    [System.SerializableAttribute()]
    public partial class Operation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lab6demo.OperationServiceReference.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExpenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lab6demo.OperationServiceReference.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExpense {
            get {
                return this.IsExpenseField;
            }
            set {
                if ((this.IsExpenseField.Equals(value) != true)) {
                    this.IsExpenseField = value;
                    this.RaisePropertyChanged("IsExpense");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/financialplanner.Data")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lab6demo.OperationServiceReference.Category[] ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lab6demo.OperationServiceReference.Category ParentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lab6demo.OperationServiceReference.Category[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lab6demo.OperationServiceReference.Category Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperationServiceReference.IOperationService")]
    public interface IOperationService {
        
        // CODEGEN: Generating message contract since element name currency from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Create", ReplyAction="http://tempuri.org/IOperationService/CreateResponse")]
        lab6demo.OperationServiceReference.CreateResponse Create(lab6demo.OperationServiceReference.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Create", ReplyAction="http://tempuri.org/IOperationService/CreateResponse")]
        System.Threading.Tasks.Task<lab6demo.OperationServiceReference.CreateResponse> CreateAsync(lab6demo.OperationServiceReference.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Read", ReplyAction="http://tempuri.org/IOperationService/ReadResponse")]
        lab6demo.OperationServiceReference.Operation[] Read(lab6demo.OperationServiceReference.Purse obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperationService/Read", ReplyAction="http://tempuri.org/IOperationService/ReadResponse")]
        System.Threading.Tasks.Task<lab6demo.OperationServiceReference.Operation[]> ReadAsync(lab6demo.OperationServiceReference.Purse obj);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="http://tempuri.org/", Order=0)]
        public lab6demo.OperationServiceReference.CreateRequestBody Body;
        
        public CreateRequest() {
        }
        
        public CreateRequest(lab6demo.OperationServiceReference.CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public lab6demo.OperationServiceReference.Purse purse;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string currency;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public lab6demo.OperationServiceReference.Category category;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string note;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string place;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool isExpense;
        
        public CreateRequestBody() {
        }
        
        public CreateRequestBody(lab6demo.OperationServiceReference.Purse purse, double sum, string name, string currency, lab6demo.OperationServiceReference.Category category, string note, System.DateTime date, string place, bool isExpense) {
            this.purse = purse;
            this.sum = sum;
            this.name = name;
            this.currency = currency;
            this.category = category;
            this.note = note;
            this.date = date;
            this.place = place;
            this.isExpense = isExpense;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public lab6demo.OperationServiceReference.CreateResponseBody Body;
        
        public CreateResponse() {
        }
        
        public CreateResponse(lab6demo.OperationServiceReference.CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateResult;
        
        public CreateResponseBody() {
        }
        
        public CreateResponseBody(bool CreateResult) {
            this.CreateResult = CreateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperationServiceChannel : lab6demo.OperationServiceReference.IOperationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationServiceClient : System.ServiceModel.ClientBase<lab6demo.OperationServiceReference.IOperationService>, lab6demo.OperationServiceReference.IOperationService {
        
        public OperationServiceClient() {
        }
        
        public OperationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab6demo.OperationServiceReference.CreateResponse lab6demo.OperationServiceReference.IOperationService.Create(lab6demo.OperationServiceReference.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public bool Create(lab6demo.OperationServiceReference.Purse purse, double sum, string name, string currency, lab6demo.OperationServiceReference.Category category, string note, System.DateTime date, string place, bool isExpense) {
            lab6demo.OperationServiceReference.CreateRequest inValue = new lab6demo.OperationServiceReference.CreateRequest();
            inValue.Body = new lab6demo.OperationServiceReference.CreateRequestBody();
            inValue.Body.purse = purse;
            inValue.Body.sum = sum;
            inValue.Body.name = name;
            inValue.Body.currency = currency;
            inValue.Body.category = category;
            inValue.Body.note = note;
            inValue.Body.date = date;
            inValue.Body.place = place;
            inValue.Body.isExpense = isExpense;
            lab6demo.OperationServiceReference.CreateResponse retVal = ((lab6demo.OperationServiceReference.IOperationService)(this)).Create(inValue);
            return retVal.Body.CreateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab6demo.OperationServiceReference.CreateResponse> lab6demo.OperationServiceReference.IOperationService.CreateAsync(lab6demo.OperationServiceReference.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab6demo.OperationServiceReference.CreateResponse> CreateAsync(lab6demo.OperationServiceReference.Purse purse, double sum, string name, string currency, lab6demo.OperationServiceReference.Category category, string note, System.DateTime date, string place, bool isExpense) {
            lab6demo.OperationServiceReference.CreateRequest inValue = new lab6demo.OperationServiceReference.CreateRequest();
            inValue.Body = new lab6demo.OperationServiceReference.CreateRequestBody();
            inValue.Body.purse = purse;
            inValue.Body.sum = sum;
            inValue.Body.name = name;
            inValue.Body.currency = currency;
            inValue.Body.category = category;
            inValue.Body.note = note;
            inValue.Body.date = date;
            inValue.Body.place = place;
            inValue.Body.isExpense = isExpense;
            return ((lab6demo.OperationServiceReference.IOperationService)(this)).CreateAsync(inValue);
        }
        
        public lab6demo.OperationServiceReference.Operation[] Read(lab6demo.OperationServiceReference.Purse obj) {
            return base.Channel.Read(obj);
        }
        
        public System.Threading.Tasks.Task<lab6demo.OperationServiceReference.Operation[]> ReadAsync(lab6demo.OperationServiceReference.Purse obj) {
            return base.Channel.ReadAsync(obj);
        }
    }
}
